# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_studyfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
    ]
