# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lecturer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='number',
            new_name='section_number',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
    ]
