# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160801_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
    ]
