# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_section_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=140)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
